market_prj/mainapp/urls.py
from django.urls import path
from mainapp import views, api_views



app_name = 'mainapp'

urlpatterns = [
    path('', views.main, name='main'),

    path("countries/", views.country_list, name="countries_list"),
    path("regions/", views.regions_list, name="regions_list"),

    path("hotels/", views.hotel_list, name="hotel_list"),
    path("hotels/<int:pk>/", views.hotel_detail, name="hotel_detail"),

    path("hotels/<int:hotel_id>/rooms/", views.room_list, name="room_list"),

    path("rooms/<int:pk>/", views.room_detail, name="room_detail"),

    path("bookings/", views.booking_list, name="booking_list"),  # Список бронирований текущего пользователя
    path("booking/create/", views.booking_create, name="booking_create"),  # Создать бронирование

    #path("hotels/<int:hotel_id>/review/", views.review_create, name="review_create"),

    path('hotel/<int:hotel_id>/reviews/', views.hotel_reviews, name='hotel_reviews'),
    path("hotels/<int:hotel_id>/review/", views.review_create, name="review_create"), # Создать отзыв для отеля

    path('api/hotels/', api_views.api_hotels, name='api_hotels'),
    path('api/hotel/<int:hotel_id>/review', api_views.api_hotels_review, name='api_hotels_review'),
]

market_prj/market_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
path('', include('mainapp.urls', namespace='mainapp')),
    path('userapp/',include('userapp.urls', namespace='userapp')),
    path('orderapp/', include('orderapp.urls', namespace='orderapp')),

    path("accounts/", include("django.contrib.auth.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market_prj/orderapp/urls.py
from django.urls import path
from . import views


app_name = 'orderapp'

urlpatterns = [
    path('', views.order_list, name='order_list'),
    path('create/', views.order_create, name='order_create'),
    path('<int:pk>/', views.order_detail, name='order_detail'),
    path('<int:pk>/confirm/', views.order_confirm, name='order_confirm'),
    path('<int:pk>/cancel/', views.order_cancel, name='order_cancel'),
    path('success/', views.order_success, name='order_success'),

]

market_prj/userapp/urls.py
from django.urls import path
import userapp.views as userapp


app_name = 'userapp'

urlpatterns = [
    path('login/', userapp.login, name='login'),
    path('logout/', userapp.logout, name='logout'),
    path('register/', userapp.register, name='register'),
    path('profile/', userapp.profile, name='profile'),

    path('profile/edit/', userapp.profile_edit, name='profile_edit')


]

market_prj/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <a class="navbar-brand" href="{% url 'mainapp:main' %}">Солнечное настроение!</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">

        <!-- Страны -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Страны
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'mainapp:countries_list' %}">Список стран</a></li>

          </ul>
        </li>

        <!-- Регионы -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Регионы
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'mainapp:regions_list' %}">Список регионов</a></li>

          </ul>
        </li>

        <!-- Отели -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Отели
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'mainapp:hotel_list' %}">Список отелей</a></li>

          </ul>
        </li>

        <!-- Бронирования -->
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mainapp:booking_list' %}">Мои бронирования</a>
          <a class="nav-link" href="{% url 'orderapp:order_list' %}">Мои заказы</a>
        </li>
        {% endif %}

        <!-- Профиль / Вход / Выход -->
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link text-danger" href="{% url 'userapp:logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'userapp:profile' %}">Профиль</a>
        </li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'userapp:login' %}">Войти</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'userapp:register' %}">Регистрация</a></li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>